# Generated by Django 5.1.4 on 2025-02-19 09:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0002_alter_student_student_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_phone',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 10 digits.', regex='^\\d{10}$')]),
        ),
    ]
